// <auto-generated />
using System;
using GulfHrBackend.DLL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GulfHrBackend.DLL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240214074930_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GulfHrBackend.Models.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("GulfHrBackend.Models.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("GulfHrBackend.Models.NotificationSchedule", b =>
                {
                    b.Property<Guid>("NotificationScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IfHoliday")
                        .HasColumnType("int");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TillEndDate")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("NotificationScheduleId");

                    b.ToTable("NotificationSchedules");
                });

            modelBuilder.Entity("GulfHrBackend.Models.NotificationScheduledOns", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("NotificationScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScheduleOn")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NotificationScheduledOns");
                });

            modelBuilder.Entity("GulfHrBackend.Models.NotificationTimes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<Guid>("NotificationScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NotificationTimes");
                });

            modelBuilder.Entity("GulfHrBackend.Models.ReportSchedule", b =>
                {
                    b.Property<Guid>("ReportScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EndsOn")
                        .HasColumnType("int");

                    b.Property<int>("EndsOnAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndsOnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExportFileType")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportFrequency")
                        .HasColumnType("int");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReportScheduleId");

                    b.ToTable("ReportSchedules");
                });

            modelBuilder.Entity("GulfHrBackend.Models.ReportScheduleRecipients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReportScheduleId");

                    b.ToTable("ReportScheduleRecipients");
                });

            modelBuilder.Entity("GulfHrBackend.Models.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmailTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NotificationScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("NotificationScheduleId");

                    b.HasIndex("ReportScheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("GulfHrBackend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GulfHrBackend.Models.ReportScheduleRecipients", b =>
                {
                    b.HasOne("GulfHrBackend.Models.ReportSchedule", null)
                        .WithMany("ReportScheduleRecipients")
                        .HasForeignKey("ReportScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GulfHrBackend.Models.Schedule", b =>
                {
                    b.HasOne("GulfHrBackend.Models.NotificationSchedule", "NotificationSchedule")
                        .WithMany()
                        .HasForeignKey("NotificationScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GulfHrBackend.Models.ReportSchedule", "ReportSchedule")
                        .WithMany()
                        .HasForeignKey("ReportScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationSchedule");

                    b.Navigation("ReportSchedule");
                });

            modelBuilder.Entity("GulfHrBackend.Models.ReportSchedule", b =>
                {
                    b.Navigation("ReportScheduleRecipients");
                });
#pragma warning restore 612, 618
        }
    }
}
